# Generated by Django 2.2.15 on 2020-10-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180411_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='displayname',
            field=models.CharField(blank=True, help_text='显示姓名', max_length=32, null=True, verbose_name='显示姓名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trainee_type',
            field=models.IntegerField(choices=[(0, '实习医生'), (1, '住院医师'), (2, '进修医生')], default=0, help_text='学员身份', verbose_name='学员身份'),
        ),
    ]
