# Generated by Django 2.2.15 on 2022-08-22 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='栏目名称', max_length=200, verbose_name='栏目名称')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='栏目创建时间', verbose_name='栏目创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, help_text='分类唯一标识', max_length=32, null=True, verbose_name='分类id')),
                ('doc_name', models.CharField(help_text='文档名称', max_length=200, verbose_name='文档名称')),
                ('is_public', models.BooleanField(default=True, help_text='是否公开', verbose_name='是否公开')),
                ('file_type', models.CharField(help_text='文件类型', max_length=200, verbose_name='文件类型')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, help_text='文档上传时间', verbose_name='文档上传时间')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now, help_text='文档更新时间', verbose_name='文档更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, help_text='文档唯一标识', max_length=32, verbose_name='文档id')),
                ('user_id', models.CharField(db_index=True, help_text='用户唯一标识', max_length=32, verbose_name='用户id')),
                ('download_date', models.DateTimeField(default=django.utils.timezone.now, help_text='文档下载时间', verbose_name='文档下载时间')),
            ],
        ),
    ]
