# Generated by Django 2.2.15 on 2020-09-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_auto_20200920_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceinfo',
            name='select_items',
            field=models.CharField(blank=True, help_text='选项文本', max_length=2000, null=True, verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='subject',
            name='index_order',
            field=models.IntegerField(default=0, help_text='索引编号', verbose_name='索引编号'),
        ),
        migrations.AddField(
            model_name='subject',
            name='item_order',
            field=models.IntegerField(default=0, help_text='单项编号', verbose_name='单项编号'),
        ),
    ]
