# Generated by Django 2.2.15 on 2020-09-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20200921_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name_add',
            new_name='subject_name_abb',
        ),
    ]
