# Generated by Django 2.2.15 on 2020-09-20 22:59

from django.db import migrations
from competition.models import Department, Subject

def forwards_department_func(apps, schema_editor):
    Department = apps.get_model("competition", "Department")
    db_alias = schema_editor.connection.alias
    Department.objects.using(db_alias).bulk_create([
        Department(id=1, department_name=0),
        Department(id=2, department_name=1),
        Department(id=3, department_name=2),
        Department(id=4, department_name=3),
        Department(id=5, department_name=4),
    ])

def reverse_department_func(apps, schema_editor):
    Department = apps.get_model("competition", "Department")
    db_alias = schema_editor.connection.alias
    Department.objects.using(db_alias).all().delete()

def forwards_subject_func(apps, schema_editor):
    Subject = apps.get_model("competition", "Subject")
    db_alias = schema_editor.connection.alias
    Subject.objects.using(db_alias).bulk_create([
        Subject(id=1, department_id=1, index_order="1", item_order="1", subject_name="总论", subject_name_abb="绪论"),
        Subject(id=2, department_id=1, index_order="2", item_order="1", subject_name="流行性感冒", subject_name_abb="流感"),
        Subject(id=3, department_id=1, index_order="2", item_order="2", subject_name="流行性腮腺炎", subject_name_abb="流行性腮腺炎"),
        Subject(id=4, department_id=1, index_order="2", item_order="3", subject_name="麻疹", subject_name_abb="麻疹"),
        Subject(id=5, department_id=1, index_order="2", item_order="4", subject_name="水痘和带状疱疹", subject_name_abb="水痘和带状疱疹"),
        Subject(id=6, department_id=1, index_order="2", item_order="5", subject_name="传单", subject_name_abb="传单"),
        Subject(id=7, department_id=1, index_order="2", item_order="6", subject_name="病毒性肝炎", subject_name_abb="肝炎"),
        Subject(id=8, department_id=1, index_order="2", item_order="7", subject_name="肠道病毒感染", subject_name_abb="肠道病毒感染"),
        Subject(id=9, department_id=1, index_order="2", item_order="8", subject_name="乙脑", subject_name_abb="乙脑"),
        Subject(id=10, department_id=1, index_order="2", item_order="9", subject_name="肾综合征出血", subject_name_abb="肾综合征出血"),
        Subject(id=11, department_id=1, index_order="2", item_order="10", subject_name="登革热", subject_name_abb="登革热"),
        Subject(id=12, department_id=1, index_order="2", item_order="11", subject_name="狂犬病", subject_name_abb="狂犬病"),
        Subject(id=13, department_id=1, index_order="2", item_order="12", subject_name="艾滋病", subject_name_abb="艾滋病"),
        Subject(id=14, department_id=1, index_order="2", item_order="13", subject_name="非典", subject_name_abb="非典"),
        Subject(id=15, department_id=1, index_order="2", item_order="14", subject_name="禽流感", subject_name_abb="禽流感"),
        Subject(id=16, department_id=1, index_order="2", item_order="15", subject_name="风疹", subject_name_abb="风疹"),
        Subject(id=17, department_id=1, index_order="2", item_order="16", subject_name="出血热", subject_name_abb="出血热"),
        Subject(id=18, department_id=1, index_order="3", item_order="1", subject_name="伤寒", subject_name_abb="伤寒"),
        Subject(id=19, department_id=1, index_order="3", item_order="2", subject_name="姜虫病", subject_name_abb="姜虫病"),
        Subject(id=20, department_id=1, index_order="3", item_order="3", subject_name="人粒细胞无形体病", subject_name_abb="人粒细胞无形体病"),
        Subject(id=21, department_id=1, index_order="4", item_order="4", subject_name="猩红热", subject_name_abb="猩红热"),
        Subject(id=22, department_id=1, index_order="4", item_order="5", subject_name="流脑", subject_name_abb="流脑"),
        Subject(id=23, department_id=1, index_order="4", item_order="6", subject_name="白喉", subject_name_abb="白喉"),
        Subject(id=24, department_id=1, index_order="4", item_order="7", subject_name="沙门菌感染", subject_name_abb="沙门菌感染"),
        Subject(id=25, department_id=1, index_order="4", item_order="8", subject_name="感染性腹泻", subject_name_abb="感染性腹泻"),
        Subject(id=26, department_id=1, index_order="4", item_order="9", subject_name="菌痢", subject_name_abb="菌痢"),
        Subject(id=27, department_id=1, index_order="4", item_order="10", subject_name="霍乱", subject_name_abb="霍乱"),
        Subject(id=28, department_id=1, index_order="4", item_order="11", subject_name="布病", subject_name_abb="布病"),
        Subject(id=29, department_id=1, index_order="4", item_order="12", subject_name="炭疽", subject_name_abb="炭疽"),
        Subject(id=30, department_id=1, index_order="4", item_order="13", subject_name="鼠疫", subject_name_abb="鼠疫"),
        Subject(id=31, department_id=1, index_order="4", item_order="14", subject_name="肺结核", subject_name_abb="肺结核"),
        Subject(id=32, department_id=1, index_order="4", item_order="15", subject_name="结核性脑膜炎", subject_name_abb="结核性脑膜炎"),
        Subject(id=33, department_id=1, index_order="4", item_order="16", subject_name="败血症", subject_name_abb="败血症"),
        Subject(id=34, department_id=1, index_order="4", item_order="17", subject_name="感染性休克", subject_name_abb="感染性休克"),
        Subject(id=35, department_id=1, index_order="5", item_order="1", subject_name="钩体病", subject_name_abb="钩体病"),
        Subject(id=36, department_id=1, index_order="5", item_order="2", subject_name="梅毒", subject_name_abb="梅毒"),
        Subject(id=37, department_id=1, index_order="5", item_order="3", subject_name="莱姆病", subject_name_abb="莱姆病"),
        Subject(id=38, department_id=1, index_order="5", item_order="4", subject_name="回归热", subject_name_abb="回归热"),
        Subject(id=39, department_id=1, index_order="6", item_order="1", subject_name="隐球菌病", subject_name_abb="隐球菌病"),
        Subject(id=40, department_id=1, index_order="6", item_order="2", subject_name="耶氏肺胞菌病", subject_name_abb="耶氏肺胞菌病"),
        Subject(id=41, department_id=1, index_order="6", item_order="3", subject_name="曲霉病", subject_name_abb="曲霉病"),
        Subject(id=42, department_id=1, index_order="6", item_order="4", subject_name="真菌", subject_name_abb="真菌"),
        Subject(id=43, department_id=1, index_order="7", item_order="1", subject_name="阿米巴病", subject_name_abb="阿米巴病"),
        Subject(id=44, department_id=1, index_order="7", item_order="2", subject_name="疟疾", subject_name_abb="疟疾"),
        Subject(id=45, department_id=1, index_order="7", item_order="3", subject_name="弓形虫病", subject_name_abb="弓形虫病"),
        Subject(id=46, department_id=1, index_order="8", item_order="1", subject_name="血吸虫病", subject_name_abb="血吸虫"),
        Subject(id=47, department_id=1, index_order="8", item_order="2", subject_name="并殖吸虫病", subject_name_abb="并殖吸虫病"),
        Subject(id=48, department_id=1, index_order="8", item_order="3", subject_name="华枝睾吸虫病", subject_name_abb="华枝睾吸虫病"),
        Subject(id=49, department_id=1, index_order="8", item_order="4", subject_name="丝虫病", subject_name_abb="丝虫病"),
        Subject(id=50, department_id=1, index_order="8", item_order="5", subject_name="绦虫病", subject_name_abb="绦虫病"),
        Subject(id=51, department_id=1, index_order="8", item_order="6", subject_name="囊尾蚴病", subject_name_abb="囊尾蚴"),
        Subject(id=52, department_id=1, index_order="8", item_order="7", subject_name="附红体病", subject_name_abb="附红体病"),
        Subject(id=53, department_id=1, index_order="8", item_order="8", subject_name="包虫病", subject_name_abb="包虫病"),
        Subject(id=54, department_id=1, index_order="8", item_order="8", subject_name="兰州包虫病", subject_name_abb="兰州包虫病"),
        Subject(id=55, department_id=1, index_order="8", item_order="9", subject_name="黑热病", subject_name_abb="黑热病"),
        Subject(id=56, department_id=1, index_order="9", item_order="1", subject_name="抗生素", subject_name_abb="抗生素"),
    ])

def reverse_subject_func(apps, schema_editor):
    Subject = apps.get_model("competition", "Subject")
    db_alias = schema_editor.connection.alias
    Subject.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_auto_20200921_0658'),
    ]

    operations = [
      migrations.RunPython(forwards_department_func, reverse_department_func),
      migrations.RunPython(forwards_subject_func, reverse_subject_func),
    ]
